# notesproxy completion                                    -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/bashly-framework/completely)
# Modifying it manually is not recommended

_notesproxy_completions_node_flag_state() {
  case "$1:$2" in
    2:-l|2:--location) return 2 ;;
    2:-e|2:--editor) return 2 ;;
    2:-c|2:--category) return 2 ;;
    2:-a|2:--autoopen) return 2 ;;
    5:-l|5:--location) return 2 ;;
    5:-e|5:--editor) return 2 ;;
    5:-c|5:--category) return 2 ;;
    5:-a|5:--autoopen) return 2 ;;
    6:-e|6:--editor) return 2 ;;
    9:-l|9:--location) return 2 ;;
    9:-e|9:--editor) return 2 ;;
    9:-c|9:--category) return 2 ;;
    9:-a|9:--autoopen) return 2 ;;
  esac

  return 1
}

_notesproxy_completions_option_seen() {
  local completed_option option_name
  for completed_option in "${completed_options[@]}"; do
    for option_name in "$@"; do
      [[ "$completed_option" == "$option_name" ]] && return 0
    done
  done

  return 1
}

_notesproxy_completions_resolve_node() {
  node_id=0
  node_word_count=0
  positional_index=0

  local word
  for word in "${non_options[@]}"; do
    case "$node_id:$word" in
      0:note)
        node_id=1
        node_word_count=1
        ;;
      0:n)
        node_id=1
        node_word_count=1
        ;;
      0:config)
        node_id=8
        node_word_count=1
        ;;
      0:c)
        node_id=8
        node_word_count=1
        ;;
      0:interactive)
        node_id=11
        node_word_count=1
        ;;
      0:i)
        node_id=11
        node_word_count=1
        ;;
      1:create)
        node_id=2
        node_word_count=2
        ;;
      1:c)
        node_id=2
        node_word_count=2
        ;;
      1:delete)
        node_id=3
        node_word_count=2
        ;;
      1:d)
        node_id=3
        node_word_count=2
        ;;
      1:list)
        node_id=4
        node_word_count=2
        ;;
      1:ls)
        node_id=4
        node_word_count=2
        ;;
      1:edit)
        node_id=5
        node_word_count=2
        ;;
      1:e)
        node_id=5
        node_word_count=2
        ;;
      1:open)
        node_id=6
        node_word_count=2
        ;;
      1:o)
        node_id=6
        node_word_count=2
        ;;
      1:nuke)
        node_id=7
        node_word_count=2
        ;;
      1:n)
        node_id=7
        node_word_count=2
        ;;
      8:edit)
        node_id=9
        node_word_count=2
        ;;
      8:e)
        node_id=9
        node_word_count=2
        ;;
      8:list)
        node_id=10
        node_word_count=2
        ;;
      8:ls)
        node_id=10
        node_word_count=2
        ;;
      *)
        break
        ;;
    esac
  done

  positional_index=$((${#non_options[@]} - node_word_count))
}

_notesproxy_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=
  if ((COMP_CWORD > 0)); then
    prev=${COMP_WORDS[$((COMP_CWORD - 1))]}
  fi

  local completed=()
  if ((COMP_CWORD > 1)); then
    completed=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi

  local non_options=()
  local completed_options=()
  local node_id=
  local node_word_count=-1
  local positional_index=0
  local invalid_completion=0
  local flag_state=0
  _notesproxy_completions_resolve_node

  local skip_next=0
  for word in "${completed[@]}"; do
    if ((skip_next)); then
      skip_next=0
      continue
    fi

    if [[ "${word:0:1}" == "-" ]]; then
      _notesproxy_completions_node_flag_state "$node_id" "$word"
      flag_state=$?
      if (( flag_state == 1 )); then
        invalid_completion=1
        break
      fi

      completed_options+=("$word")
      if (( flag_state == 2 )); then
        skip_next=1
      fi
      continue
    fi

    non_options+=("$word")
    _notesproxy_completions_resolve_node
  done

  COMPREPLY=()
  (( invalid_completion )) && return

  case "$node_id:$prev" in
    2:-l|2:--location)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      compopt -o filenames
      return
      ;;
    2:-e|2:--editor)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A command -- "$cur")
      return
      ;;
    2:-c|2:--category)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(np cls)" -- "$cur")
      return
      ;;
    2:-a|2:--autoopen)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "true false" -- "$cur")
      return
      ;;
    5:-l|5:--location)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      compopt -o filenames
      return
      ;;
    5:-e|5:--editor)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A command -- "$cur")
      return
      ;;
    5:-c|5:--category)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(np cls)" -- "$cur")
      return
      ;;
    5:-a|5:--autoopen)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "true false" -- "$cur")
      return
      ;;
    6:-e|6:--editor)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A command -- "$cur")
      return
      ;;
    9:-l|9:--location)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      compopt -o filenames
      return
      ;;
    9:-e|9:--editor)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A command -- "$cur")
      return
      ;;
    9:-c|9:--category)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(np cls)" -- "$cur")
      return
      ;;
    9:-a|9:--autoopen)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "true false" -- "$cur")
      return
      ;;
  esac

  if [[ "${cur:0:1}" != "-" ]] && (( positional_index == 0 )); then
    case "$node_id" in
      0)
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "note n config c interactive i" -- "$cur")
        return
        ;;
      1)
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "create c delete d list ls edit e open o nuke n" -- "$cur")
        return
        ;;
      8)
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "edit e list ls" -- "$cur")
        return
        ;;
    esac
  fi

  if [[ "${cur:0:1}" == "-" ]]; then
    case "$node_id" in
      0)
        local words=()
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      1)
        local words=()
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      2)
        local words=()
        _notesproxy_completions_option_seen "-l" "--location" || words+=("-l" "--location")
        _notesproxy_completions_option_seen "-e" "--editor" || words+=("-e" "--editor")
        _notesproxy_completions_option_seen "-c" "--category" || words+=("-c" "--category")
        _notesproxy_completions_option_seen "-a" "--autoopen" || words+=("-a" "--autoopen")
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      3)
        local words=()
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      4)
        local words=()
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      5)
        local words=()
        _notesproxy_completions_option_seen "-l" "--location" || words+=("-l" "--location")
        _notesproxy_completions_option_seen "-e" "--editor" || words+=("-e" "--editor")
        _notesproxy_completions_option_seen "-c" "--category" || words+=("-c" "--category")
        _notesproxy_completions_option_seen "-a" "--autoopen" || words+=("-a" "--autoopen")
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      6)
        local words=()
        _notesproxy_completions_option_seen "-e" "--editor" || words+=("-e" "--editor")
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      7)
        local words=()
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      8)
        local words=()
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      9)
        local words=()
        _notesproxy_completions_option_seen "-l" "--location" || words+=("-l" "--location")
        _notesproxy_completions_option_seen "-e" "--editor" || words+=("-e" "--editor")
        _notesproxy_completions_option_seen "-c" "--category" || words+=("-c" "--category")
        _notesproxy_completions_option_seen "-a" "--autoopen" || words+=("-a" "--autoopen")
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      10)
        local words=()
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      11)
        local words=()
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
    esac
  fi

  case "$node_id:$positional_index" in
    2:0)
      return
      ;;
    3:0)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(np nls)" -- "$cur")
      return
      ;;
    4:0)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(np cls)" -- "$cur")
      return
      ;;
    5:0)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(np nls)" -- "$cur")
      return
      ;;
    6:0)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(np nls)" -- "$cur")
      return
      ;;
  esac
} &&
  complete -F _notesproxy_completions notesproxy np

# ex: filetype=sh
